name: fts-monitoring

services:
  prometheus:
    image: prom/prometheus:v3.11.3@sha256:e4254400b85610324913f0dc4acf92603d9984e7519414c5a12811aa6146acc3
    volumes:
    - ./prometheus.yml:/prometheus.yml
    command:
    - --enable-feature=native-histograms
    - --config.file=/prometheus.yml
    networks: [ "monitoring", "clinical-domain", "research-domain", "trust-center" ]
    ports:
    - :9090

  grafana:
    image: grafana/grafana:13.0.1@sha256:0f86bada30d65ef9d0183b90c1e2682ac92d53d95da8bed322b984ea78a4a73a
    volumes:
    - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/grafana-datasources.yaml
    - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboards.yaml
    - ./grafana/dashboards:/etc/grafana/dashboards
    - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
    - 42128:3000
    networks: [ "monitoring" ]
networks:
  monitoring:
  clinical-domain:
    external: true
    name: fts-test_clinical-domain
  research-domain:
    external: true
    name: fts-test_research-domain
  trust-center:
    external: true
    name: fts-test_trust-center
