management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "prometheus" ]

  metrics:
    distribution:
      slo:
        http.server.requests: 25,100,250,500,1000,10000
        http.client.requests: 25,100,250,500,1000,2000,3000,4000,5000,6000,7000,8000,9000,10000
        deidentify: 25,100,250,500,1000,10000

security:
  endpoints:
  - path: /api/v2/**
    role: client

runner:
  maxSendConcurrency: 32
  maxConcurrentProcesses: 4
  processTtlSeconds: 86400
