{
 "title": "HTTP Requests",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CDA",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_bucket{job=\"cda\"}) by (le)"
    }
   ]
  },
  {
   "title": "Active Client Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(client_name) (http_client_requests_active_seconds_sum)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCA",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_bucket{job=\"tca\"}) by (le)"
    }
   ]
  },
  {
   "title": "Active Server Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(job) (http_server_requests_active_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RDA",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_bucket{job=\"rda\"}) by (le)"
    }
   ]
  }
 ]
}