{
 "title": "HTTP Request Duration",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "CDA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "fetchBundle",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(le) (rate(http_client_requests_seconds_bucket{job=\"cda\", uri=\"/api/v2/cd/consented-patients/fetch\"}[1m]))"
    },
    {
     "expr": "sum by(le) (rate(http_client_requests_seconds_bucket{job=\"cda\", uri=\"/api/v2/cd/consented-patients/fetch-all\"}[1m]))"
    }
   ]
  },
  {
   "title": "fetchBundle",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (http_client_requests_seconds_bucket{job=\"cda\", uri=\"/api/v2/cd/consented-patients/fetch\"})"
    },
    {
     "expr": "sum by(le) (http_client_requests_seconds_bucket{job=\"cda\", uri=\"/api/v2/cd/consented-patients/fetch-all\"})"
    }
   ]
  },
  {
   "title": "fetchPatientBundleResolvePID",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(le) (rate(http_client_requests_seconds_bucket{job=\"cda\", uri=\"/fhir/Patient\"}[1m]))"
    }
   ]
  },
  {
   "title": "fetchPatientBundleResolvePID",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (http_client_requests_seconds_bucket{job=\"cda\", uri=\"/fhir/Patient\"})"
    }
   ]
  },
  {
   "title": "fetchEverything",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(le) (rate(http_client_requests_seconds_bucket{job=\"cda\", uri=\"/fhir/Patient/{id}/$everything\"}[1m]))"
    }
   ]
  },
  {
   "title": "fetchEverything",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (http_client_requests_seconds_bucket{job=\"cda\", uri=\"/fhir/Patient/{id}/$everything\"})"
    }
   ]
  },
  {
   "title": "fetchEverything p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(http_client_requests_seconds_bucket{job=\"cda\", uri=\"/fhir/Patient/{id}/$everything\"}[1m]))"
    }
   ]
  },
  {
   "title": "fetchEverything p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_client_requests_seconds_bucket{job=\"cda\", uri=\"/fhir/Patient/{id}/$everything\"}[1m]))"
    }
   ]
  },
  {
   "title": "fetchEverything p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(http_client_requests_seconds_bucket{job=\"cda\", uri=\"/fhir/Patient/{id}/$everything\"}[1m]))"
    }
   ]
  },
  {
   "title": "deidentify",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(le) (rate(deidentify_seconds_bucket[1m]))"
    }
   ]
  },
  {
   "title": "deidentify",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (deidentify_seconds_bucket)"
    }
   ]
  },
  {
   "title": "fetchTransportMapping",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by(le) (rate(http_client_requests_seconds_bucket{job=\"cda\", uri=\"/api/v2/cd/transport-mapping\"}[1m]))"
    }
   ]
  },
  {
   "title": "fetchTransportMapping",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (http_client_requests_seconds_bucket{job=\"cda\", uri=\"/api/v2/cd/transport-mapping\"})"
    }
   ]
  },
  {
   "title": "sendBundleToRda",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum by(le) (rate(http_client_requests_seconds_bucket{job=\"cda\", uri=\"/api/v2/process/{project}/patient\"}[1m]))"
    }
   ]
  },
  {
   "title": "sendBundleToRda",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (http_client_requests_seconds_bucket{job=\"cda\", uri=\"/api/v2/process/{project}/patient\"})"
    }
   ]
  },
  {
   "title": "Check Status of RDASendBundle",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by(le) (rate(http_client_requests_seconds_bucket{job=\"cda\", uri=\"/api/v2/process/status/UUID\"}[1m]))"
    }
   ]
  },
  {
   "title": "Check Status of RDASendBundle",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (http_client_requests_seconds_bucket{job=\"cda\", uri=\"/api/v2/process/status/UUID\"})"
    }
   ]
  },
  { "title": "TCA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "fetchConsentPageFromGics",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum by(le) (rate(http_client_requests_seconds_bucket{job=\"tca\", client_name=\"gics\"}[1m]))"
    }
   ]
  },
  {
   "title": "fetchConsentPageFromGics",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (http_client_requests_seconds_bucket{job=\"tca\", client_name=\"gics\"})"
    }
   ]
  },
  {
   "title": "fetchOrCreatePseudonymsOnGpas",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "sum by(le) (rate(http_client_requests_seconds_bucket{job=\"tca\", uri=\"/ttp-fhir/fhir/gpas/$pseudonymizeAllowCreate\"}[1m]))"
    }
   ]
  },
  {
   "title": "fetchOrCreatePseudonymsOnGpas",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (http_client_requests_seconds_bucket{job=\"tca\", uri=\"/ttp-fhir/fhir/gpas/$pseudonymizeAllowCreate\"})"
    }
   ]
  },
  { "title": "RDA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "fetchResearchMapping",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum by(le) (rate(http_client_requests_seconds_bucket{job=\"rda\", uri=\"/api/v2/rd/research-mapping\"}[1m]))"
    }
   ]
  },
  {
   "title": "fetchResearchMapping",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (http_client_requests_seconds_bucket{job=\"rda\", uri=\"/api/v2/rd/research-mapping\"})"
    }
   ]
  },
  {
   "title": "deidentify",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "sum by(le) (rate(deidentify_seconds_bucket[1m]))"
    }
   ]
  },
  {
   "title": "deidentify",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (deidentify_seconds_bucket)"
    }
   ]
  },
  {
   "title": "sendBundleToHds",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "sum by(le) (rate(http_client_requests_seconds_bucket{job=\"rda\", uri=\"/fhir\"}[1m]))"
    }
   ]
  },
  {
   "title": "sendBundleToHds",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (http_client_requests_seconds_bucket{job=\"rda\", uri=\"/fhir\"})"
    }
   ]
  }
 ]
}