{
 "title": "HTTP Request Retries",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "CDA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "fetchBundle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "fetchBundle_retries_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "fetchPatientBundleResolvePID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "fetchPatientBundleResolvePID_retries_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "fetchEverything",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "fetchEverything_retries_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "fetchTransportIdsAndDateShiftingValues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "fetchTransportIdsAndDateShiftingValues_retries_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sendBundleToRda",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "sendBundleToRda_retries_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "TCA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "fetchConsentPageFromGics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "fetchConsentPageFromGics_retries_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "fetchOrCreatePseudonymsOnGpas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "fetchOrCreatePseudonymsOnGpas_retries_total",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RDA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "fetchPseudonymsForTransportId",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "fetchPseudonymsForTransportIds_retries_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sendBundleToHds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    { "expr": "sendBundleToHds_retries_total", "legendFormat": "__auto" }
   ]
  }
 ]
}