spring:
  ssl:
    bundle:
      pem:
        cd-agent:
          keystore:
            certificate: classpath:/client-cd-agent.crt
            private-key: classpath:/client-cd-agent.key
          truststore:
            certificate: classpath:/ca.crt
        rd-agent:
          keystore:
            certificate: classpath:/client-rd-agent.crt
            private-key: classpath:/client-rd-agent.key
          truststore:
            certificate: classpath:/ca.crt
        unauthorized:
          truststore:
            certificate: classpath:/ca.crt
        self-signed:
          keystore:
            certificate: classpath:/client-no-ca.crt
            private-key: classpath:/client-no-ca.key
          truststore:
            certificate: classpath:/ca.crt

server:
  ssl:
    client-auth: want

test:
  webclient:
    cd-agent:
      ssl:
        bundle: cd-agent
    rd-agent:
      ssl:
        bundle: rd-agent
    unauthorized:
      ssl:
        bundle: unauthorized
    incorrect:
      ssl:
        bundle: self-signed

security:
  auth:
    client-cert:
      users:
      - username: cd-agent
        role: cd
      - username: rd-agent
        role: rd
