server:
  port: 9090

projects:
  directory: "../.github/test/cd-agent/projects"

security:
  auth:
    oauth2:
      issuer: http://localhost:8080/realms/fts

spring:
  security:
    oauth2:
      client:
        registration:
          agent:
            authorization-grant-type: client_credentials
            client-id: FTSnext
            client-secret: ATCYS7wR0tjRSrXBpOVZ9ibSMvcthAvo
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/fts

test:
  webclient:
    default:
      auth:
        oauth2:
          registration: agent
