name: Pages

on:
  push:
    tags: [ "v*.*.*" ]
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "opened", "reopened", "synchronize", "closed" ]
  merge_group:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Check out Git repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Setup Node
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
      with:
        node-version: 21
        cache: npm
        cache-dependency-path: 'docs/package-lock.json'

    - name: Build
      working-directory: docs
      env:
        DOCS_BASE: "/${{ github.event.repository.name }}/"
      run: make build

    - name: Setup Pages
      uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
      with:
        path: docs/.vitepress/dist

  deploy:
    runs-on: ubuntu-24.04
    if: github.ref_name == github.event.repository.default_branch
    needs: [ build ]
    permissions:
      pages: write
      id-token: write
    environment:
      name: pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4

  preview:
    runs-on: ubuntu-24.04
    if: github.ref_name != github.event.repository.default_branch
    needs: [ build ]
    permissions:
      pages: write
      id-token: write
    environment:
      name: pages/preview
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: rossjrw/pr-preview-action@v1
      with:
        source-dir: docs/.vitepress/dist
        preview-branch: main
        umbrella-dir: docs/pre
