name: Pages

on:
  push:
    tags: [ "v*.*.*" ]
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:
  workflow_dispatch:

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-24.04
    steps:
    - name: Check out Git repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

    - name: Set up JDK 21
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4
      with:
        distribution: 'temurin'
        java-version: 21
        cache: 'maven'

    - name: Build Images
      run: make all

    - name: Get Latest Release Tag using GitHub Script
      id: gh_latest_tag
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
      with:
        script: |
          const latestRelease = await github.rest.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });

          const latestTag = latestRelease.data.tag_name || "v0.0.0"; // Default if no release
          console.log(`Latest tag: ${latestTag}`);
          core.setOutput("latest_tag", latestTag);

    - name: Build OpenAPI Specs
      working-directory: docs
      run: make generate-openapi

    - name: Setup Node
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
      with:
        node-version: 21
        cache: npm
        cache-dependency-path: 'docs/package-lock.json'

    - name: Build Documentation
      working-directory: docs
      env:
        DOCS_BASE: "/${{ github.event.repository.name }}/"
        VITE_LATEST_RELEASE: ${{ steps.gh_latest_tag.outputs.latest_tag }}
      run: make build

    - name: Setup Pages
      uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
      with:
        path: docs/.vitepress/dist

  deploy:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-24.04
    needs: [ build ]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
