name: Publish Release

on:
  release:
    types: [ released ]

# Declare default permissions as read only.
permissions: read-all

jobs:
  pages:
    runs-on: ubuntu-24.04
    permissions:
      actions: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
      with:
        egress-policy: audit

    - name: Trigger Pages Build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh workflow run Pages --ref main --repo ${{ github.repository }}
