name: Publish Release

on:
  release:
    types: [ released ]

# Declare default permissions as read only.
permissions: read-all

jobs:
  pages:
    runs-on: ubuntu-24.04
    permissions:
      actions: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit

    - name: Trigger Pages Build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
        RELEASE_TAG: ${{ github.event.release.tag_name }}
      run: gh workflow run Pages --ref main --repo "$REPO" -f release_tag="$RELEASE_TAG"
